name: Vite CI

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - feature/#33-cicd

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' 
      
      - name: delete
        run: rm -f yarn.lock package-lock.json

      - name: Install
        run: |
          npm install 
          
      - name: Run tests
        run: |
          npm run test || true
